### ISSUE TITLE
Export custom classes

### ISSUE THREAD

**Issue by hboylan** [mattlewis92/generator-angular-library#15]
Hey, this generator was super helpful for publishing a custom angular2 module, but I'm having trouble adding a custom service.

For some reason the default module/component import just fine after publishing, but ones I add myself can't be found. I've tried a component and service like this, but neither work:

```typescript
// test.component
import {Component} from '@angular/core';

@Component({
  selector: 'test-component',
  template: '<p>This is just a test</p>'
})
export class TestComponent {}
```

```typescript
// test.service
import { Injectable } from '@angular/core';

@Injectable()
export class TestService {}
```

```typescript
// index.ts
export * from './ng2Test.module';

// all components that will be codegen'd need to be exported for AOT to work
export * from './test.service';
export * from './test.component';
export * from './helloWorld.component';
```

```typescript
// test.module
import {NgModule} from '@angular/core';
import {HttpModule} from '@angular/http';
import {TestService} from './test.service';
import {TestComponent} from './test.component';
import {HelloWorld} from './helloWorld.component';

@NgModule({
  declarations: [HelloWorld, TestComponent],
  imports: [HttpModule],
  exports: [HelloWorld, TestComponent],
  providers: [TestService]
})
export class Ng2TestModule {}
```

Only Ng2TestModule and HelloWorld are available for import after publishing the NPM package.

**Comment by mattlewis92** [comment]
I'm sorry but I can't see what's going wrong, would it be possible for you to put together a repo that demonstrates your issue? Thanks!

**Comment by hboylan** [comment]
Ha, yea sorry for dumping all that code. Thanks in advance.

I'm just confused why I can import TestComponent, but can't import TestService from [this angular2-module](https://github.com/hboylan/ng2-module-test) into [this angular-cli app](https://github.com/hboylan/ng2-cli-test/blob/74636f3dde9ae36b8eaa6297d049bed99003cc47/src/app/app.module.ts#L5).

**Comment by mattlewis92** [comment]
Sorry but I can't reproduce your issue. I added this into my app:
```
import {Ng2TestModule, HelloWorld, TestComponent, TestService} from 'ng2-module-test';
console.log(Ng2TestModule, HelloWorld, TestComponent, TestService);
```

and it worked fine for me:

<img width="489" alt="screen shot 2016-11-06 at 10 39 03" src="https://cloud.githubusercontent.com/assets/6425649/20036892/44e3e756-a40d-11e6-8dc8-7a6b8b1c2a86.png">

Is it just errors from your IDE that you're getting that's saying the module doesn't exist? Maybe it needs to reindex to find the new imports?

**Comment by hboylan** [comment]
Wooooowwww. You're right, the Atom package I'm using has a refresh button that rebuilt the indexes and made the error go away. I thought just saving was doing the same thing.

Thanks for the help! Will definitely be using this lib.

**Comment by mattlewis92** [comment]
Glad you got it sorted 👍
