### ISSUE TITLE
What needs to change to use templateUrl in components?

### ISSUE THREAD

**Issue by mraible** [mattlewis92/generator-angular-library#18]
I'm trying to switch my library from using embedded templates in components to using `templateUrl`. I want to do this so users of my library can override the `templateUrl`. 

However, when I try to move the HTML to a template in the same directory, I get errors in my tests.

```
Error: This test module uses the component LoginComponent which is using a "templateUrl", but they were never compiled. Please call "TestBed.compileComponents" before your test. in test/entry.ts (line 37582)
```

I have the following in `login.component.spec.ts`:

```
  beforeEach(() => {
    TestBed.configureTestingModule({
      imports: [StormpathModule]
    });
    TestBed.compileComponents();
  });
```

I was able to get the HTML templates to load by using angular2-template-loader and raw-loader:

```
    loaders: [
      {
        test: /\.ts$/,
        loaders: ['awesome-typescript-loader', 'angular2-template-loader?keepUrl=true'],
        exclude: [/\.(spec|e2e)\.ts$/, /node_modules/]
      },
      /* Embed files. */
      {
        test: /\.(html|css)$/,
        loader: 'raw-loader',
        exclude: /\.async\.(html|css)$/
      },
      /* Async loading. */
      {
        test: /\.async\.(html|css)$/,
        loaders: ['file?name=[name].[hash].[ext]', 'extract']
      }
    ]
```

**Comment by mraible** [comment]
I was able to fix this by changing `karma.conf.js` to use a similar setup:

```
loaders: [
{
  test: /\.ts$/,
  loaders: ['awesome-typescript-loader', 'angular2-template-loader?keepUrl=true'],
  exclude: /node_modules/
},
{
  test: /\.(html|css)$/,
  loader: 'raw-loader',
  exclude: /\.async\.(html|css)$/
},
{
  test: /\.async\.(html|css)$/,
  loaders: ['file?name=[name].[hash].[ext]', 'extract']
},
{
  test: /sinon.js$/, loader: 'imports-loader?define=>false,require=>false'
}
],
```

From the little research I've done, it doesn't seem like you can easily override templateUrls.

**Comment by mraible** [comment]
I'm closing this issue since I figured out [how to do it](https://github.com/stormpath/stormpath-sdk-angular/pull/17/files). If you know how to override templateUrls in 3rd party components, I'd love to hear about it!

**Comment by mattlewis92** [comment]
Glad you got it resolved :) 

Regarding dynamic user templates, currently there is not an amazing solution to do this that is AoT compatible. You need to leverage `<template>` tags and the `ngTemplateOutlet` directive. There is an example of how to do this [here](https://github.com/mattlewis92/angular-confirmation-popover/blob/master/src/confirmationPopoverWindow.component.ts#L16-L54) and a test that shows it in action [here](https://github.com/mattlewis92/angular-confirmation-popover/blob/master/test/angular-confirmation-popover.spec.ts#L387-L424). Maybe in the future this will get easier 😄

**Comment by mraible** [comment]
Thanks for the tip @mattlewis92. However, this shows how to override it in a test - and `TestBed` allows overriding a template. How would you do it if you wanted to override the template after in your production code? [This](http://stackoverflow.com/a/35035466/65681) seems to be an option, but it's not pretty.

**Comment by mattlewis92** [comment]
Ah sorry that was a bit misleading, ignore that it's in a test and just focus on the [components template](https://github.com/mattlewis92/angular-confirmation-popover/blob/master/test/angular-confirmation-popover.spec.ts#L390-L409) (imagine it was just a template on a standard component). Note how the custom template is wrapped in a template tag, is bound to the local variable `#customTemplate` and then passed as an input to the `mwlConfirmationPopover` component. There is a really good write up [here](https://medium.com/@isaacplmann/if-you-think-you-need-the-angular-2-runtime-jit-compiler-2ed4308f7515#.s3lz412am) that explains the different options available.

**Comment by mraible** [comment]
Thanks - works great!
