### ISSUE TITLE
how to deal with templateUrl?

### ISSUE THREAD

**Issue by kuyoonjo** [mattlewis92/generator-angular-library#34]
Unhandled Promise rejection: Failed to load template.html ; Zone: <root> ; Task: Promise.then ; Value: Failed to load template.html undefined

```
import { Component, OnInit, Input } from '@angular/core';
import { ConfirmationService, Message, LazyLoadEvent, SelectItem } from 'primeng/primeng';
import { YcjsAPI, YcjsRequest, YcjsRequestPaginateData } from '@ycjs/core';
import { YcjsAuth } from '@ycjs/auth';

@Component({
  selector: 'ycjs-admin-crud',
  templateUrl: './template.html',
  providers: [ConfirmationService]
})
export class YcjsAdminCRUDComponent implements OnInit {
 // ...
}

```

**Comment by mattlewis92** [comment]
You'll need to add the [angular2-template-loader](https://github.com/TheLarkInn/angular2-template-loader) to your webpack config. Hope that helps! 😃

**Comment by tonimoeckel** [comment]
Could you give me a hint how to configure angular2-template-loader? Its working for me in the development environment. But as soon as I run `ngc -p tsconfig-ngc.json` the templateUrl stays in the generated dist files. I thought ngc should render the templateUrl as template string? Did I forget something?

**Comment by mattlewis92** [comment]
angular2-template-loader is only for JiT mode, when running ngc + AoT it isn't needed. I only ever use inline templates and never templateUrl's so am not sure about the issue you're getting, I'd recommend posting a repo + asking on stackoverflow.
