### ISSUE TITLE
Gh-pages command not functioning

### ISSUE THREAD

**Issue by ArthurMauricioDelgadillo** [mattlewis92/generator-angular-library#35]
Hi, I create a new repo and execute the command npm run gh-pages but it's not working...saying that the "-b option in the compodoc command doesn't exist". So I go to the compodoc repository and found that it has been removed from the options in latest versions. When I remove the -b, then appears another problem, saying 

> error: pathspec "build"  did not match any file(s) known to git. 

The same happens to "demo" and "docs", I saw that this words (build, demo and docs) was part of the gh-pages command: `git commit -m 'chore: build demo and docs'`

Now I'm using this command in my tsconfig (remove the commit -m & the -b):
```json
{
"compodoc": "compodoc -p tsconfig-compodoc.json -d docs --disableGraph --disableCoverage --disablePrivateOrInternalSupport",
"gh-pages": "git checkout gh-pages && git merge master --no-edit --no-ff && npm run build:demo && npm run compodoc && git add .",
}
```
It works but I think if the commit -m inside of the gh-pages command functions, it will be better 
Pd: sorry for my bad english I'm latinoamerican

**Comment by mattlewis92** [comment]
Oops, thanks for reporting! Will be fixed in the next release.
