### ISSUE TITLE
copyfiles command only works in Linux

### ISSUE THREAD

**Issue by StefH** [mattlewis92/generator-angular-library#36]
This command fails on windows:
```
"copyfiles": "cp package.json LICENSE README.md CHANGELOG.md dist/",
```
fails on windows. Is there a workaround for this?

**Update**
I installed http://cygwin-lite.sourceforge.net/index.html

**Comment by mattlewis92** [comment]
I've replaced the cp command with an npm lib that should be more cross compatible. Thanks for reporting! 😄
