### ISSUE TITLE
test\entry.ts small error in import

### ISSUE THREAD

**Issue by StefH** [mattlewis92/generator-angular-library#39]
`import 'rxjs';` should be `import 'rxjs/Rx';`

**Comment by mattlewis92** [comment]
The rxjs package.json aliases `rxjs/Rx` to be the same as `rxjs` via the package.json's main file: https://unpkg.com/rxjs@5.2.0/package.json

**Comment by StefH** [comment]
This was a TSLint error.

**Comment by mattlewis92** [comment]
Ah ok, which rule was that out of curiosity?

**Comment by StefH** [comment]
For the rules : See https://github.com/StefH/angular-odata-es5 project
