### ISSUE TITLE
npm run gh-pages error ?

### ISSUE THREAD

**Issue by StefH** [mattlewis92/generator-angular-library#41]
```
> compodoc -p tsconfig-compodoc.json -d docs -b /angular-odata-es5/docs/ --disableGraph --disableCoverage --disablePrivateOrInternalSupport


  error: unknown option `-b'
```

**Comment by mattlewis92** [comment]
Just remove that flag from the script, it's already fixed on the latest version of the generator: https://github.com/mattlewis92/generator-angular-library/commit/8224da467c8ac2e326513acd2aa466cd3330d677
