### ISSUE TITLE
gh-pages , push fails?

### ISSUE THREAD

**Issue by StefH** [mattlewis92/generator-angular-library#43]
```
fatal: The current branch gh-pages has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin gh-pages
```

**Comment by mattlewis92** [comment]
The install script should do this for you when scaffolding the app: https://github.com/mattlewis92/generator-angular-library/blob/master/generators/app/index.js#L183

If it didn't work because the project was scaffolded outside of the git repo then you'll need to execute that command manually.
