### ISSUE TITLE
How to use CHANGELOG.md ?

### ISSUE THREAD

**Issue by StefH** [mattlewis92/generator-angular-library#47]
Can you please tell me how to use the changelog?

My file is currently a bit strange ;-)

https://github.com/StefH/angular-odata-es5/blob/master/CHANGELOG.md#change-log

**Comment by mattlewis92** [comment]
Sure thing, it's explained here:
https://github.com/bcoe/conventional-changelog-standard/blob/master/convention.md

Tl;dr anything with fix or feat will appear in the change log, for everything else that you don't want to appear use chore, refactor, style etc

You can also use "npm run commit" to launch the wizard to better help you generate the commits.

**Comment by StefH** [comment]
Hello @mattlewis92 Sorry, I cannot understand this process.

I'll try to add the steps which I think should do, can you **please** update / correct ?

1. Make a change in a file (let's assume it's a fix)
2. Increase the version in package.json and add release-notes to package.json
3. Stage files
4. `npm run commit` to use the interface to create the text
5. `npm run release:git`
6. Optionally do `npm run gh-pages`

Between 4 and 5, it does not work because of some error like : `Your branch is ahead of 'origin/master' by 1 commit.`

**Comment by mattlewis92** [comment]
Ah I see where you're going wrong. Features, fixes should be their own independent changes. The release script is designed to release a set of commits all in own go. So your workflow should look something like
1/ Make a change in a file (let's assume it's a fix)
2/ Stage files
3/ `npm run commit` to use the interface to create the text
4/ Repeat steps 1-3 as many times as you want until you're ready to release
5/ Increase the version in package.json (but don't commit it)
6/ `npm run release:git`
7/ Optionally do `npm run gh-pages`

It might help to see the workflow I use in a real project: https://github.com/mattlewis92/angular-calendar/commits/master

Hope that helps! 😄

**Comment by StefH** [comment]
Thanks.
