### ISSUE TITLE
"@angular/core": ">=2.0.0 <5.0.0" does not work correct ?

### ISSUE THREAD

**Issue by StefH** [mattlewis92/generator-angular-library#48]
See : https://github.com/mattlewis92/generator-angular-library/blob/master/generators/app/templates/_package.json#L95

Gives this warning when doing `npm install`

> warning "angular-odata-es5@0.1.1" has incorrect peer dependency "@angular/core@>=2.0.0 <5.0.0".

**Comment by mattlewis92** [comment]
Are you using angular 4 in your app?

**Comment by StefH** [comment]
Yes

**Comment by mattlewis92** [comment]
I think it's because anything with RC or beta doesn't actually count as stable, the stable version is due to land tonight though so the problem will literally solve itself overnight 😀
