### ISSUE TITLE
Question : you used yarn, will this not conflict with npm ?

### ISSUE THREAD

**Issue by StefH** [mattlewis92/generator-angular-library#49]

**Comment by mattlewis92** [comment]
You can use them side by side. They both do the same thing (creating a node_modules folder of all your dependencies), apart from that yarn uses a lock file, is deterministic and a lot faster than npm.

**Comment by StefH** [comment]
I noticed that using _yarn_ for running a **angular cli** does not work.

**Comment by mattlewis92** [comment]
Doesn't work in what way? I've installed the cli before with yarn without issues, they even have a config option to use yarn as well.
