### ISSUE TITLE
Latest version is broken : unable to load templateUrl

### ISSUE THREAD

**Issue by StefH** [mattlewis92/generator-angular-library#55]
This code:
```js
import { templateSourceUrl } from '@angular/compiler/src/compile_metadata';
import { Component } from '@angular/core';

@Component({
  selector: 'tst-demo-app',
  // template: '<tst-hello-world></tst-hello-world>'
  templateUrl: './demo.component.html'
})
export class DemoComponent {}
```

Gives error in browser console:

**http://localhost:8000/demo.component.html --> 404**
and
**Unhandled Promise rejection: Failed to load demo.component.html ; Zone: <root> ; Task: Promise.then ; Value: Failed to load demo.component.html undefined**

For demo project : see https://github.com/StefH/angular-test

**Comment by StefH** [comment]
I think that **contentBase: 'demo'** must be added?

```js
devServer: {
    port: 8000,
    inline: true,
    hot: true,
    historyApiFallback: true,
    contentBase: 'demo'
  },
```

**Comment by mattlewis92** [comment]
It's a breaking change in angular4: https://angular-update-guide.firebaseapp.com/

<img width="849" alt="screen shot 2017-03-28 at 18 55 40" src="https://cloud.githubusercontent.com/assets/6425649/24419752/2b2423f8-13e8-11e7-8443-a561cb5f9495.png">
