### ISSUE TITLE
Angular 4 gives warning when running test

### ISSUE THREAD

**Issue by StefH** [mattlewis92/generator-angular-library#56]
When using Angular 4, you get this warning:

`
WARNING in ./~/@angular/core/@angular/core.es5.js
5889:15-36 Critical dependency: the request of a dependency is an expression
`

This can be solved like:
https://github.com/AngularClass/angular2-webpack-starter/issues/993

**Comment by mattlewis92** [comment]
This has already been done: https://github.com/mattlewis92/generator-angular-library/commit/873de25c0c9d04d150f0fc4f9b50a3707dd30753
