### ISSUE TITLE
html & css

### ISSUE THREAD

**Issue by kyxw007** [mattlewis92/generator-angular-library#57]
my angular library contain component with html template and css， I got  error  like “Failed to load hello-word.componrnt.html”

**Comment by mattlewis92** [comment]
As per the [angular packaging guidelines](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/edit#heading=h.dhi53tt0wmgv), you should write your component templates and styles as inline templates rather than using template / styleurls.

**Comment by kyxw007** [comment]
Thank you for your answer !  So there is no solution to apply templateUrl & styleUrls to angular library ?

**Comment by kyxw007** [comment]
in addition，how angular library handle images

**Comment by mattlewis92** [comment]
Not that will work with AoT, see this talk for more info: https://www.youtube.com/watch?v=unICbsPGFIA

Angular doesn't know anything about images. As long as they're not too big you could probably inline them with the url-loader: https://github.com/webpack-contrib/url-loader
