### ISSUE TITLE
Karma code coverage not working under windows

### ISSUE THREAD

**Issue by etiscan** [mattlewis92/generator-angular-library#58]
When using the library generator under windows the code coverage with karma-coverage-istanbul-reporter is not working. Neither the coverage console output is shown nor the files are generated. Running the "npm run test" command with different consoles (Powershell, Git Bash and Windows console) ended with the same result (see: [console-log.txt](https://github.com/mattlewis92/generator-angular-library/files/1141963/console-log.txt))

I don't think it's a problem with karma-coverage-istanbul-reporter  because the code coverage is working in following project https://github.com/karin-exini/coverage-istanbul-reporter-path under windows. Also, it's working with OSX and Linux. So it could be a problem with the Karma configuration or some npm packages.

Could you please look after the problem? 

Regards

**Comment by mattlewis92** [comment]
I don't have a window machine handy but at a guess it's because of the path separator. Should be fixed now in `v2.12.1`. Thanks for reporting!
