### ISSUE TITLE
loglevel missing

### ISSUE THREAD

**Issue by krzysztofsaja** [mattlewis92/generator-angular-library#62]
Hi, I'm just testing your generator and I saw, that it lacks one devDependency: loglevel. In order to run it without errors I need to `yarn add loglevel --save-dev`

**Comment by mattlewis92** [comment]
It's an issue with webpack-dev-server which gets installed by this generator: https://github.com/webpack/webpack-dev-server/issues/1000

There's already a PR to fix it, no doub it'll be released in a couple hours 😀
