### ISSUE TITLE
Error when yarn not installed

### ISSUE THREAD

**Issue by pvamshi** [mattlewis92/generator-angular-library#67]
I don't have the exact error message but here is what happens. If yarn is not installed, `caniuseyarn` returns false and `packageManager` value is not asked to the user. 
But while evaluating the template we are checking for its value which is undefined. May be we should initialize it to 'npm' as the default value.
Forgot to mention : Awesome work, just what I was looking . pure. perfect. thanks

**Comment by mattlewis92** [comment]
Whoops, should be fixed now. Thanks for reporting! 😄
