### ISSUE TITLE
Styles for Demo site

### ISSUE THREAD

**Issue by wleelavivat** [mattlewis92/generator-angular-library#70]
Hi,

Would it be possible to allow styles (scss) to be included and used for the demo site?

Do you have any advice to implement it?

Thanks,

**Comment by mattlewis92** [comment]
You need to add the [sass / css / style loader](https://github.com/webpack-contrib/sass-loader) to the demo sites webpack config. You can then import the styles somewhere in your app like so `import './styles.scss'`
