### ISSUE TITLE
Live Reload doesnt support templateUrl

### ISSUE THREAD

**Issue by pratikthecook** [mattlewis92/generator-angular-library#72]
While Live reloading using the `npm start` command & my component consist of 
```
/**
 * Created by pratik on 15/2/18.
 */
import { Component, OnInit } from '@angular/core';

@Component({
 selector: 'code-explorer',
 templateUrl: 'code-explorer.component.html'
})

export class CodeExplorerComponent implements OnInit {
 constructor() { }

 ngOnInit() { }
}
```
i get this error on console
`http://localhost:8000/code-explorer.component.html 404 (Not Found)`

It seems live reload doesnt inline style or the HMR doesnt support templateUrl.

**Comment by mattlewis92** [comment]
There isn't support for this with this generator by default, but you may be able to get it working with: https://github.com/gdi2290/angular-hmr (I've never tried it so YMMV)

**Comment by pratikthecook** [comment]
Ok thanks ! Gr8 work btw
